language: java
sudo: true
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.m2/
jdk:
  - openjdk8
services:
  - docker
before_install:
  - chmod +x ./mvnw
after_script:
  - docker build --force-rm -t party --label party . && docker images
before_deploy:
  - chmod +x ./dock-push.sh
deploy:
  skip_cleanup: true
  provider: script
  script: bash ./dock-push.sh