language: java
sudo: true
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.m2/
jdk:
  - openjdk8
services:
  - docker
before_install:
  - chmod a+x ./mvnw
after_script:
  - docker build --force-rm -t norg/party:latest . && docker images
deploy:
  provider: script
  script: bash dock_push.sh